### ISSUE TITLE
object type select is not working

### ISSUE THREAD

**Issue by Suu0313** [schabrolles/kubectl-commander#1]
```sh
$ kubectl commander
/home/user-name/.krew/bin/kubectl-commander: line 60: oc: command not found
```

I think it should be `$k8cmd` there, not `oc`.

**Comment by schabrolles** [comment]
Good catch,
I corrected and pushed to main branch

**Comment by Suu0313** [comment]
Thank you for the quick fix!

**Comment by schabrolles** [comment]
YW, this is a "young" plugin I made for my needs (mostly openshift) and some other bugs should be there.

You should be able to update your plugin with krew
