### ISSUE TITLE
invalid color specification: label:#87ff00

### ISSUE THREAD

**Issue by skotaru-cisco** [schabrolles/kubectl-commander#2]
kubectl commander
invalid color specification: label:#87ff00

for any object selection same error message is coming up. 

fzf --version
0.20.0

uname -a
Linux skotaru-lnx 5.4.0-190-generic #210-Ubuntu SMP Fri Jul 5 17:03:38 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

Srinivas Kotaru

**Comment by gauthiersiri** [comment]
Update fzf to the latest version ;)
